-- CREATE DATABASE ToDo;
-- USE MarselaToDo;

/*
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);
*/


/*
CREATE TABLE tasks (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
title VARCHAR(255) NOT NULL,
description TEXT,
deadline DATE NOT NULL,
completed BOOLEAN NOT NULL DEFAULT false,
FOREIGN KEY (user_id) REFERENCES users(id)
);
*/


/*
ALTER TABLE tasks
ADD COLUMN priority INT NOT NULL;
*/